# .goreleaser.yml
# Build customization
builds:
  -
    binary: akamai-netlist
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.appVer=$TRAVIS_TAG
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: mac
  format: binary
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"